### ISSUE TITLE
isObjectProperty(): Argument of type 'AbstractBaseProperty | AbstractBaseProperty[]' is not assignable to parameter of type 'BasicProperty'

### ISSUE THREAD

**Issue by Sleavely** [etothepii4/satisfactory-file-parser#5]
Using v1.1.1 it seems I cant pass `object.properties.anything` to `isObjectProperty()` or the other type guards without the type error `Argument of type 'AbstractBaseProperty | AbstractBaseProperty[]' is not assignable to parameter of type 'BasicProperty'`.

Are the entries in PropertiesMap always a BasicProperty?

https://github.com/etothepii4/satisfactory-file-parser/blob/2f238b3fdeb61c596e59cb5712719e0b7e1aaa46/src/parser/satisfactory/types/property/generic/BasicProperty.ts#L4-L6

### Reproducible

https://github.com/Sleavely/satisfactory-savegame-prometheus-exporter/blob/942f7216491453cd66c63de15ceea589025465b0/src/metricGroups/resources.ts#L27

(If you don't want to clone the repo you can [open it in github.dev](https://github.dev/Sleavely/satisfactory-savegame-prometheus-exporter/blob/942f7216491453cd66c63de15ceea589025465b0/src/metricGroups/resources.ts) and wait for a minute while it installs the dependencies)

On the lines below I ended up simply casting the `object.properties` props to their respective types and confirmed it works(.. for now).

**Comment by etothepii4** [comment]
Appreciate the feedback!
The types are not perfectly clean i admit.
So far, all properties inherited from `BasicProperty` except the `StructProperty`. Since this is unnecessary anway, I was able to refactor the `StructProperty` and replaced the `BasicProperty` with `AbstractBaseProperty`. So every property is now simply an `AbstractBaseProperty`.
Plus, I made the type guards of the properties to accept `any`, since that is seemingly more best practice.
